// Auto-generates src/content/galleryData.js by scanning public/images subfolders
const fs = require('fs')
const path = require('path')

const imagesDir = path.resolve(__dirname, '../public/images')
const outputFile = path.resolve(__dirname, '../src/content/galleryData.js')

const CATEGORIES = [
  { key: 'training', label: 'Student Training Session', folder: 'Student Training Session', icon: '🎯' },
  { key: 'founder', label: 'Founder Stunts', folder: 'Founder Stunts', icon: '🏍️' },
  { key: 'shows', label: 'Stunt Shows', folder: 'Stunt Shows', icon: '🎪' },
  { key: 'ptp', label: 'Patna Traffic Police Collaboration', folder: 'PTP', icon: '🚓' },
  { key: 'results', label: 'Student Results', folder: 'Student Result', icon: '🏆' },
  { key: 'events', label: 'Events & Collaboration', folder: 'Event and Colloboration', icon: '🤝' },
]

const SUPPORTED_EXTS = new Set([
  '.jpg', '.jpeg', '.png', '.webp', '.gif',
  '.JPG', '.JPEG', '.PNG', '.WEBP', '.GIF',
])

const categories = CATEGORIES.map(cat => {
  const folderPath = path.join(imagesDir, cat.folder)
  let images = []
  if (fs.existsSync(folderPath)) {
    images = fs.readdirSync(folderPath)
      .filter(f => SUPPORTED_EXTS.has(path.extname(f)))
      .map(f => `/images/${cat.folder}/${f}`)
  }
  return { key: cat.key, label: cat.label, icon: cat.icon, images }
})

const output = `// AUTO-GENERATED by scripts/generate-gallery.cjs — do not edit manually
export const galleryCategories = ${JSON.stringify(categories, null, 2)}
`

fs.writeFileSync(outputFile, output, 'utf8')
console.log('Gallery data generated:', outputFile)
categories.forEach(c => console.log(`  ${c.icon} ${c.label}: ${c.images.length} images`))
